version: '3.7'

x-labels: &standard_build
  image: cucumber-example
  restart: "no"

x-labels: &number_of_builds
  total_number_of_builds: 8

services:
  one:
    <<: *standard_build
    environment:
      build_number: 1
      <<: *number_of_builds


  two:
    <<: *standard_build
    environment:
      build_number: 2
      <<: *number_of_builds

  three:
    <<: *standard_build
    environment:
      build_number: 3
      <<: *number_of_builds

  four:
    <<: *standard_build
    environment:
      build_number: 4
      <<: *number_of_builds

  five:
    <<: *standard_build
    environment:
      build_number: 5
      <<: *number_of_builds

  six:
    <<: *standard_build
    environment:
      build_number: 6
      <<: *number_of_builds

  seven:
    <<: *standard_build
    environment:
      build_number: 7
      <<: *number_of_builds

  eight:
    <<: *standard_build
    environment:
      build_number: 8
      <<: *number_of_builds