version: '3.3'



services:
  one:
    image: cucumber-example
    restart: "no"
    environment:
      build_number: 1
      total_number_of_builds: 8
    deploy: &deploy
      resources:
        limits:
          cpus: '.50'
          memory: '50M'

  two:
    image: cucumber-example
    restart: "no"
    environment:
      build_number: 2
      total_number_of_builds: 8
    <<: *deploy


  three:
    image: cucumber-example
    restart: "no"
    environment:
      build_number: 3
      total_number_of_builds: 8

  four:
    image: cucumber-example
    restart: "no"
    environment:
      build_number: 4
      total_number_of_builds: 8

  five:
    image: cucumber-example
    restart: "no"
    environment:
      build_number: 5
      total_number_of_builds: 8

  six:
    image: cucumber-example
    restart: "no"
    environment:
      build_number: 6
      total_number_of_builds: 8

  seven:
    image: cucumber-example
    restart: "no"
    environment:
      build_number: 7
      total_number_of_builds: 8

  eight:
    image: cucumber-example
    restart: "no"
    environment:
      build_number: 8
      total_number_of_builds: 8

