version: '2.0'
services:
  one:
    image: cucumber-example
    environment:
      build_number: 1
      total_number_of_builds: 3
      volumes:
        "- docker_output:/usr/bin/web-repo/output"

  two:
    image: cucumber-example
    environment:
      build_number: 2
      total_number_of_builds: 3

  three:
    image: cucumber-example
    environment:
      build_number: 2
      total_number_of_builds: 3